spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 867765250122-rj5jmfvcn3ntslu3pbgurq8uhov7l749.apps.googleusercontent.com
            client-secret: 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
            scope: profile, email
          kakao:
            client-id: 97eb88a1de40d41dbbdc28b79bd71d9e
            client-secret: 3qR9UvYSKVJ107wyFhvJSVH6B45rY5kC
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao
            client-authentication-method: POST
            authorization-grant-type: authorization_code
            scope: profile_nickname, profile_image
            client-name: Kakao

        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

  mail:
    host: smtp.gmail.com
    port: 587
    username: net1645@gmail.com
    password: ${GOOGLE_APP_KEY}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

